### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by ADanielEtech** [TopFloorTech/formtools-swiftmailer-modern#1]
Perhaps it has to do with how I installed the upgrade, but I'm having an issue.  After installation into FormTools, at first all seems well.  I configure the SMTP settings for the Module, and then click the "Test" tab to send a test email.  On clicking the Send Test Email button, I receive the error "Website cannot display page, Error 500".  After a bit of looking, I still can't seem to track down just which page it is referring to, all the pages that are referenced appear to be in the correct folders.  

Just in case the problem is in how I did the installation, here are the steps I used:
Uninstalled the old Swiftmailer Module through FormTools' Modules menu
Ftp'd the files I had downloaded from GitHub repository into the modules\swift_mailer folder.
Installed and Enabled the Module through FormTools
Filled in the SMTP information, then went to the Test Tab.

Is it possible that I also need to make some changes within some of the other FormTools Code as well ? At this point the only changes I made to files was to the files that were within the original swift_mailer folder.

I'm using FormTools 2.2.6

Thanks -

**Comment by ReplicaObscura** [comment]
@ADanielEtech It appears that you've done things right on first glance. Can you get the actual underlying error that's occurring from the web server logs by chance?

I didn't have to make any changes to the FormTools code outside of the swift_mailer module. The only difference I can see between our steps is that I didn't fully uninstall the old swiftmailer module first, I just replaced the code and re-saved the configuration.

If you are able to post the underlying error message here, I'd be happy to try and help troubleshoot the code--it's quite possible it's something very simple that's different in our environments.

**Comment by ADanielEtech** [comment]
Here are the errors I receive.  I have verified that the library file referenced ft_library.php does exist, and that there is a reference to the class 'Swift_SmtpTransport' on line 78 in that file.  I have also verified that the files in the \swift_mailer\php5\classes\ folder match the files I downloaded from the repository here.  The 'classes' folder did not exist in the original, old Swift Mailer installation, so all the files in it are the ones downloaded from this repository.  Thanks for the help, I think I'm close to this working on my installation.

[24-Aug-2016 12:08:35 America/Denver] PHP Fatal error:  Class 'Swift_SmtpTransport' not found in ../formtools/modules/swift_mailer/php5/ft_library.php on line 78
[24-Aug-2016 12:11:08 America/Denver] PHP Fatal error:  Class 'Swift_SmtpTransport' not found in ../formtools/modules/swift_mailer/php5/ft_library.php on line 78
[24-Aug-2016 12:30:02 America/Denver] PHP Fatal error:  Class 'Swift_SmtpTransport' not found in ../formtools/modules/swift_mailer/php5/ft_library.php on line 78
[25-Aug-2016 11:09:14 America/Denver] PHP Fatal error:  Class 'Swift_SmtpTransport' not found in ../formtools/modules/swift_mailer/php5/ft_library.php on line 78

**Comment by ADanielEtech** [comment]
I resolved the Class 'Swift_SmtpTransport' not found error by reloading the library.php file to my site again.

**Comment by ReplicaObscura** [comment]
Thanks for the follow-up on this issue!

Just to confirm--was the change you needed to make something due to your project, or something specific to this repo that other users may experience that try to utilize it?

**Comment by ADanielEtech** [comment]
Your code seems sound.  I had issues with an array of other things that
related to my Web host, and to the external SMTP server I was configuring.

But, I worked through all that finally, lol.

Annette
